### PR TITLE
Contract fixes

### LINKED ISSUE #195: Add ACI to contract descriptor
To don't have to provide contract source/aci in subsequent contract calls.

### PR DESCRIPTION
**Pull request by davidyuk**
closes #195

### CODE REVIEW

File: scripts/js-to-md.js [hunk 1]
```diff
@@ -35,9 +35,9 @@ function splitCodeIntoBlocks(text) {
   return content;
 }
 
-process.argv.slice(2).forEach((fileName) => {
+process.argv.slice(2).forEach(async (fileName) => {
   const inputFilePath = path.resolve(process.cwd(), fileName);
-  const text = fs.readFileSync(inputFilePath).toString();
+  const text = await fs.readFile(inputFilePath).toString();
```
Comment (thepiwo) [inline scripts/js-to-md.js:40]: there is also fs.promises natively

**Review by thepiwo — APPROVED** [review]
lgtm, just a small comment
